# syntax = docker/dockerfile:1

FROM python:3.9.13-slim-buster

WORKDIR /usr/src/app

COPY . .

COPY requirements.txt requirements.txt
RUN pip3 install --no-cache-dir -r requirements.txt

EXPOSE 80

ENV NAME World

CMD ["python","./app.py"]



